// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import {Appbar} from '@/components/layout/appbar/appbar'
// import '@/style/globals.css';

// import {
//   fontDisplay,
//   fontHeading,
//   fontInter,
//   fontRoboto,
//   fontSans,
// } from '@/lib/fonts';
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Newa Lahana",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
 
// }>) {
//   return (
//     <html lang="en">
//       <body className={(
        
//         fontRoboto.variable,
//         fontDisplay.variable,
//         fontInter.variable,
//         fontHeading.variable
//       )}
//     >
//       <Appbar/>
//         {children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Appbar} from '@/components/layout/appbar/appbar'
import '@/style/globals.css';

import {
  fontDisplay,
  fontHeading,
  fontInter,
  fontRoboto,
 
} from '@/lib/fonts';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lahana-Lunchbox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
 
}>) {
  return (
    <html lang="en">
      <body className={(
        
        fontRoboto.variable,
        fontDisplay.variable,
        fontInter.variable,
        fontHeading.variable
        
      )}
    >
      <Appbar/>
        {children}</body>
    </html>
  );
}
